apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubecoin.fullname" . }}-webui
  labels:
    component: webui
    {{- include "kubecoin.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.webui.replicaCount }}
  selector:
    matchLabels:
      component: webui
      {{- include "kubecoin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        component: webui
        {{- include "kubecoin.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "kubecoin.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.webui.podSecurityContext | nindent 8 }}
      containers:
        - name: webui
          securityContext:
            {{- toYaml .Values.webui.securityContext | nindent 12 }}
          image: {{ include "kubecoin.webui.image" . }}
          imagePullPolicy: {{ .Values.webui.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.webui.resources | nindent 12 }}
      {{- with .Values.webui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.webui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.webui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
