apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubecoin.fullname" . }}-webui
  labels:
    {{- include "kubecoin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    component: webui
    {{- include "kubecoin.selectorLabels" . | nindent 4 }}
